spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

gateway:
  downstream:
    auth-url: ${AUTH_SERVICE_URL:http://localhost:8081}
    profile-url: ${PROFILE_SERVICE_URL:http://localhost:8082}
    bidding-service-url: ${BIDDING_SERVICE_URL:http://localhost:8083}
  rate-limit:
    auth:
      replenish-rate: 3
      burst-capacity: 8
    profile:
      replenish-rate: 20
      burst-capacity: 50
    bidding-service:
      replenish-rate: 30
      burst-capacity: 100


management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    com.bido.api_gateway: DEBUG
    org.springframework.cloud.gateway: INFO

jwt:
  secret: ${JWT_SECRET_KEY}