server:
  port: 8080

spring:
  application:
    name: api-gateway

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-route
              uri: ${gateway.downstream.auth-url}
              predicates:
                - Path=/api/auth/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: ${gateway.rate-limit.replenish-rate} # tokeni/secundă regenerați
                    redis-rate-limiter.burstCapacity: ${gateway.rate-limit.burst-capacity} # maximul de tokeni
                    redis-rate-limiter.requestedTokens: 1 # fiecare request consumă 1 token
                    key-resolver: "#{@ipKeyResolver}"

management:
  endpoints:
    web:
      exposure:
        include: health